### ISSUE TITLE
SocketStream.aclose() isn't all that graceful

### ISSUE THREAD

**Issue by Nikratio** [python-trio/trio#412] opened 2018-01-20 19:56 UTC
The documentation says:

> This method may block in order to perform a “graceful” shutdown. [..] This requires sending a “goodbye” message; 

And the implementation is:

```
    async def aclose(self):
        self.socket.close()
        await _core.checkpoint()
```

For a "graceful close" of a TCP connection I would at the very least expect a call to `socket.shutdown()` first. Ideally, it would behave as https://tools.ietf.org/html/rfc7230#section-6.6 prescribes for HTTP:

>    If a server performs an immediate close of a TCP connection, there is
>    a significant risk that the client will not be able to read the last
>    HTTP response.  If the server receives additional data from the
>    client on a fully closed connection, such as another request that was
>    sent by the client before receiving the server's response, the
>    server's TCP stack will send a reset packet to the client;
>    unfortunately, the reset packet might erase the client's
>    unacknowledged input buffers before they can be read and interpreted
>    by the client's HTTP parser.
> 
>    To avoid the TCP reset problem, servers typically close a connection
>    in stages.  First, the server performs a half-close by closing only
>    the write side of the read/write connection.  The server then
>    continues to read from the connection until it receives a
>    corresponding close by the client, or until the server is reasonably
>    certain that its own TCP stack has received the client's
>    acknowledgement of the packet(s) containing the server's last
>    response.  Finally, the server fully closes the connection.

Thoughts?

**Comment by njsmith** [comment] 2018-01-20 21:47
The problem is that this depends on the details of the protocol. Even in HTTP, notice that that language only applies to servers, not to clients – clients generally go ahead and close when they're ready, and this is more efficient than waiting for the server. So I think that's the right definition of `aclose` for `SocketStream`, and if you build a higher level protocol on top of it then your higher-level protocol object's `aclose` should implement whatever makes sense for your protocol.

The Trio server example in the h11 docs has an implementation of that HTTP server logic: https://h11.readthedocs.io/en/latest/examples.html#fairly-complete-server-with-error-handling-using-trio-for-async-i-o
(It's currently called `shutdown_and_clean_up`; maybe it should be called `aclose`. That example predates all the work on standardizing cleanup interfaces in trio :-).)

But want I want to point out is, notice how in that example the actual `SocketStream` is wrapped in an HTTP class, which is the thing your program actually uses? That's the general pattern that these streams are intended to support. (In fact, `SSLStream` is exactly this kind of wrapper around another `Stream`, it just happens that the interface it consumes and the interface it provides are the same.)

**Comment by Nikratio** [comment] 2018-01-20 22:15
I agree with all what you're saying - but I think what you are doing is explaining why either (a) `aclose` isn't a good idea at all (this belongs in a higher layer), or (b) clients should not call aclose, because they don't need to terminate gracefully. I don't think you're making a good point for `aclose` behaving the way it currently does (claiming to be graceful, but just being an alias for close).

**Comment by njsmith** [comment] 2018-01-20 23:40
The reason `SocketStream` has an `aclose` method is because it implements the generic stream interface, and the generic stream interface has an `aclose` method. For example, this makes it easy to write code that works over both raw sockets and over SSL/TLS-encrypted sockets, because they export the same interface. The generic stream `aclose` method has the semantics that it attempts a graceful close – whatever that means for the particular concrete implementation – and if that fails/is cancelled, then it performs a forceful close. It happens that for a simple socket, graceful and forceful close are the same, so that's what `SocketStream.aclose` does. For `SSLStream`, they are different. (And in fact these `aclose` semantics are from `trio.abc.AsyncResource`, which is also implemented by other types beyond streams, like listeners and async files.)

**Comment by Nikratio** [comment] 2018-01-21 14:34
Hm, okay, let me try to put my thoughts differently:

- Having aclose() in the generic async stream interface only makes sense if a graceful close makes sense for every kind of async stream. So assume this is the case.
- In your own words, the aclose() implementation for SocketStream currently only behaves correctly for clients, but not for servers. So aclose() is actually going to do the wrong thing in one out of two cases.
- However, at least in plain HTTP clients don't even need to do a graceful close - they can just close the connection. So arguably, the aclose() method fails in all the cases where it makes sense to call it (when you're acting as a server).
- As far as I can see, there isn't any reason for the client to behave differently when using SSL. Why bother with a long shutdown if you can just close the socket after you received the data you wanted? Yet for SSL case the `aclose` method actually does behave graceful. 

So when deciding whether to call aclose(), we actually have the following decision tree:

Am I the client or server?
1. When client, is it plain HTTP or SSL?
  1.a. if plain HTTP, use aclose if you want speed, or a custom method if you want to be nice to the server
  1.b if SSL, use a custom method if you want speed, or aclose if you want to be nice to the server, 
2. When server, is it plain HTTP or SSL?
  2.a. if plain HTTP, use a custom method
  2.b if SSL, use aclose

I think this makes aclose() rather awkward to use in its current form. I think one way to make it easier to use would be to have aclose() *always* behave gracefully. That way you can just always use it and nothing bad will happen. And if you happen to be client and need some extra speed, you have the *option* to call close() instead.

**Comment by Nikratio** [comment] 2018-01-21 14:37
Of course, the other option to make things more consistent would be to declare that the proper definiton of "graceful" depends on the higher-level protocol. But in that case, IMC `aclose()` doesn't belong in the generic interface but only in the upper layer.

**Comment by njsmith** [comment] 2018-01-21 20:45
Just to check, you do realize that `aclose` is there only way to close a generic stream, right? It's not "here's a special method for graceful close", it's "here's the method for closing things, and btw if your object has a distinction between graceful and non-graceful close then here's how you should implement `aclose`"

**Comment by Nikratio** [comment] 2018-01-22 10:20
I thought there is aclose() for graceful close, and aclose_forcefully() for fast, potentially non-graceful close?

**Comment by njsmith** [comment] 2018-01-22 10:30
`aclose_forcefully` isn't part of the abstract interface that lots of classes have to implement, it's a single convenience function for calling an object's `aclose` method and then immediately cancelling it:

https://github.com/python-trio/trio/blob/d063d672de15edc231b14c0a9bc3673e5275a9dc/trio/_highlevel_generic.py#L20-L47

Early drafts of this APIs had `forceful_close` (synchronous) and `graceful_close` (asynchronous) as two different methods, but it turns out that `graceful_close` has to always do a `forceful_close` when cancelled *anyway*, so instead of making every `AsyncResource` class implement two separate/redundant methods, it's simpler all around if we just have one `aclose` method that does both.

**Comment by Nikratio** [comment] 2018-01-22 20:39
Ok.. so then there isn't an aclose_forcefully. But I think all my comments from above (https://github.com/python-trio/trio/issues/412#issuecomment-359252811) still apply. As it is, correctly using aclose() is rather complicated, and it would be much nicer for aclose() to always close gracefully and have a second method (ideally part of the abstract interface) that closes ungraceful.

**Comment by njsmith** [comment] 2018-01-22 23:48
When you say "it would be much nicer for `aclose()` to always close gracefully", I assume you mean that you think we should remove the behavior where it closes forcefully on error/cancellation?

But that would make it much more complicated to use! It would mean that literally every time you called `aclose`, you'd have to write something like:

```python
try:
    await obj.aclose()
except:
    obj.forceful_close()
    raise
```

or else you'd risk accidentally not closing the thing at all.

**Comment by Nikratio** [comment] 2018-01-23 05:35
No, I mean it should always attempt to be graceful, eg for the TCP stream it should first call shutdown for the write channel, and maybe wait a little until the peer closes the read channel, and then close the socket.

**Comment by njsmith** [comment] 2018-01-23 05:44
I'm afraid we're not going to do that, because like I said above, whether that's appropriate depends on the higher-level protocol and how the socket is being used, and the vast majority of programs do not use that pattern. It's much easier for the occasional code that wants that to implement it themselves on top of our generic API, than for all the codes that don't want it to always check for whether they have a `SocketStream` and if so call `aclose_forcefully`.

**Closed by njsmith** 2018-01-23 05:44 UTC

**Comment by Nikratio** [comment] 2018-01-23 10:18
I don't understand. Either your code wants to close the connection gracefully, then it should use aclose. Or it doesn't, in which case it should use some other method (close, socket.close, or aclose_forcefully). Why would you have to check whether the stream is a SocketStream?

As I said above, I think it would allow to get rid of all the two nested if-else clauses that you currently have to use if you want your code to work when acting as server or client, and over SSL or plain TCP.

**Comment by njsmith** [comment] 2018-01-23 18:40
Because for most protocols, the current implementation of `aclose` *is* a correct graceful close.

What nested if-else clauses? Are you referring to this?

> Am I the client or server?
> 1. When client, is it plain HTTP or SSL?
>    1.a. if plain HTTP, use aclose if you want speed, or a custom method if you want to be nice to the server
>    1.b if SSL, use a custom method if you want speed, or aclose if you want to be nice to the server,
> 2. When server, is it plain HTTP or SSL?
>    2.a. if plain HTTP, use a custom method
>    2.b if SSL, use aclose

The client parts of that are wrong – for an http client, calling `aclose` always closes the connection immediately (because you'll be using `SSLStream` in `https_compatible=True` mode), which is both fastest *and* nicest to the server.

The server part is correct, but like... the http spec says that if you're a server, and not doing SSL, then as a special case you should do a certain thing. It's totally appropriate that when your protocol spec says there's a special case, your protocol implementation ends up with some `if`s. It's not a `SocketStreamWithSpecialCasesForHTTPServers`.
