### ISSUE TITLE
trio.Path inconsistencies

### ISSUE THREAD

**Issue by oremanj** [python-trio/trio#917] opened 2019-02-08 07:06 UTC
Noticed these doing typing:
* glob() and rglob() probably want the same treatment as iterdir(); currently they return an iterable of unwrapped pathlib.Path objects
* trio.Path.cwd() is synchronous - is that intended? On Linux it doesn't need to hit the disk (it has a dedicated syscall, or can use `readlink /proc/self/cwd`), but I think on some other Unixes it can...

**Comment by njsmith** [comment] 2019-02-13 10:01
Marking "good first issue" for the `glob` and `rglob` fixes. The issue is: `trio.Path.glob` returns an iterable of `pathlib.Path` objects. We should convert them into `trio.Path` objects instead. And the same for `trio.Path.rglob`. `trio.Path.iterdir` has an example of how to do this.

Regarding the `cwd` thing... well, does anyone know what macOS does? Does anyone with a Mac want to run a syscall tracer to find out?

It [looks like Windows is fine](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-getcurrentdirectory):

> The current directory state written by the `SetCurrentDirectory` function is stored as a global variable in each process, therefore multithreaded applications cannot reliably use this value without possible data corruption from other threads that may also be reading or setting this value.

**Comment by pquentin** [comment] 2019-02-13 13:27
> Regarding the `cwd` thing... well, does anyone know what macOS does? Does anyone with a Mac want to run a syscall tracer to find out?

I did not manage to get this working with Python: my syscall tracer (dtruss) stops at `posix_spawn()`. However, it looks like CPython just calls `getcwd()`. Here's what `getcwd()` does on macOS 10.14 inside "/private/tmp".

```
65059/0x42b8a:  open_nocancel(".\0", 0x0, 0x0)           = 3 0
65059/0x42b8a:  fstat64(0x3, 0x7FFEE819AB10, 0x0)                = 0 0
65059/0x42b8a:  fcntl_nocancel(0x3, 0x32, 0x7F8FC9800000)                = 0 0
65059/0x42b8a:  close_nocancel(0x3)              = 0 0
65059/0x42b8a:  stat64("/private/tmp\0", 0x7FFEE819AA80, 0x0)            = 0 0
```

[This Quora answer](https://www.quora.com/How-is-getcwd-implemented-on-Mac) mentions an existing implementation. I think the current one is https://opensource.apple.com/source/Libc/Libc-1272.200.26/gen/FreeBSD/getcwd.c.auto.html.

Is this helpful?

**Comment by zthompson47** [comment] 2019-03-01 14:11
I posted issue #960 and wanted to mention that it overlaps with this issue.  I'm currently looking at how to generate an async classmethod for both ``cwd`` and ``home``.

I also might look at ``glob`` and ``rglob`` while I'm in there, and wanted some clarification.

We want to convert the returned lists of objects into lists of wrapped objects, but do was also want to eagerly load the lists into memory for ``glob`` and ``rglob`` like we do for ``iterdir``?

It looks to me like "yes" because the iterators could make calls like ``exists`` and ``is_dir`` as they step (#501).

**Comment by zthompson47** [comment] 2019-03-06 01:34
> 
> Is this helpful?

It helped me figure out how to do a syscall trace, so thanks for that, pquentin.  I reproduced your results for ``getcwd()``, and I put this together to test ``Path.home`` on macOS 10.14:

```
#include <unistd.h>
#include <sys/types.h>
#include <pwd.h>

int main() {
    struct passwd *pws;
    pws = getpwuid(geteuid());
    return 0;
}
```
produces:
```
geteuid(0x0, 0x0, 0x0)		 = 0 0
geteuid(0x0, 0x0, 0x0)		 = 0 0
getrlimit(0x1008, 0x7FFEEEA3A970, 0x0)		 = 0 0
open_nocancel("/etc/master.passwd\0", 0x0, 0x1B6)		 = 3 0
fstat64(0x3, 0x7FFEEEA3A9E0, 0x0)		 = 0 0
fstat64(0x3, 0x7FFEEEA398C8, 0x0)		 = 0 0
read_nocancel(0x3, "##\n# User Database\n# \n# Note that this file is consulted directly only when the system is running\n# in single-user mode.  At other times this information is provided by\n# Open Directory.\n#\n# See the opendirectoryd(8) man page for additional information abo", 0x1000)		 = 4096 0
close_nocancel(0x3)		 = 0 0
```
As my passwd file implies, most cases would get a home directory by other means, and pathlib.Path would end up getting it from ``os.environ['HOME']``.

**Comment by njsmith** [comment] 2019-05-01 21:15
@zthompson47 did your PRs fix this?

**Comment by zthompson47** [comment] 2019-05-01 22:48
> @zthompson47 did your PRs fix this?

Yes they did, and I can close this issue now.  Have fun at PyCon!

**Closed by zthompson47** 2019-05-01 22:48 UTC
Labels: good first issue
