### ISSUE TITLE
0.22.0: version not updated

### ISSUE THREAD

**Issue by kloczek** [python-trio/trio#2583] opened 2023-03-01 11:54 UTC
Looks like `trio.__vesion__` has not been updated before tagging
https://github.com/python-trio/trio/blob/v0.22.0/trio/_version.py#L1-L3

**Comment by A5rocks** [comment] 2023-03-01 14:27
Just a note that the published release has the correct `trio.__version__`, just that tag does not have it.

Do you have a use case that requires this? I'm sure we can find a way but at first glance I'm not quite sure how we can update a tag like that -- maybe make a `v0.22.0` branch and add a fixing commit?

**Comment by kloczek** [comment] 2023-03-01 14:58
Yes however I'm using VCS tar ball becaue I want to have guarantee that on top of release tree it would be possible to apply any patches from git commmits 😋 
Just please remeber about update version before tagging (best woild be if you will be using Ci target to make release (chechout tree, update version and than tag and push that tag to github automatically). 😃

**Comment by pquentin** [comment] 2023-03-07 07:48
This is a duplicate of https://github.com/python-trio/trio/issues/2485. I did not get to make a release, would you like to give it a try @A5rocks?

**Closed by pquentin** 2023-03-07 07:48 UTC

**Comment by A5rocks** [comment] 2023-03-07 13:26
I'd love to make a release after a few of @richardsheridan's PRs land (and I suppose that would be a minor version bump?)
