### ISSUE TITLE
MultiError is un-unpicklable

### ISSUE THREAD

**Issue by andyljones** [python-trio/trio#2543] opened 2023-01-20 00:25 UTC
```python
import trio
import pickle
me = trio.MultiError([ValueError()])
pickle.loads(pickle.dumps(eg))
```
throws a
```shell
----> 1 pickle.loads(pickle.dumps(me))

TypeError: MultiError.__new__() takes 2 positional arguments but 3 were given
```
error, I think because of some conflict with how ExceptionGroups - which expect a message as well as an error list - are constructed.

trio version 0.22.0, python 3.10.6

**Comment by jakkdl** [comment] 2023-05-05 12:52
I cannot reproduce this, tried it on all python versions 3.7-3.11
is it still an issue @andyljones ?

**Comment by jakkdl** [comment] 2023-05-16 10:26
closing this one, feel free to reopen if it can be reproduced

**Comment by hotpxl** [comment] 2023-05-24 03:50
The key to the repro is having 2 exceptions in `MultiError`, otherwise `MultiError.__new__` will just return that one exception
```
me = trio.MultiError([ValueError()])
pickle.loads(pickle.dumps(me))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: MultiError.__new__() takes 2 positional arguments but 3 were given
```

Tested on master
```
commit 855f5fd72e9e126b8dae2348a918427d7a1f38cd (HEAD -> master, origin/master, origin/HEAD)
Author: John Litborn <11260241+jakkdl@users.noreply.github.com>
Date:   Tue May 16 14:09:02 2023 +0200
```
and Python 3.10.11

**Comment by jakkdl** [comment] 2023-05-24 14:56
Thanks @hotpxl! Wrote a PR that fixes it :)

**Closed** 2023-05-30 08:33 UTC
Labels: exception handling
