### ISSUE TITLE
PermissionError: [WinError 5] Access is Denied when importing trio

### ISSUE THREAD

**Issue by chrisbeardy** [python-trio/trio#2688] opened 2023-07-06 11:19 UTC
Trio version 0.22.1
Python version 3.11.4 and 3.10.12 tried
Windows 10

After creating a venv, ttrying to import trio in a python console gives a permission error.

Tthis only happens with 0.22.1, reverting to 0.22.0 works just fine

ttraceback:
```
Traceback (most recent call last):
  File "C:\Users\chrisb\AppData\Local\Programs\Python\Python310\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\chrisb\GitWS\async_and_thread_test\venv2\lib\site-packages\trio\__init__.py", line 22, in <module>
    from ._core import (
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\chrisb\GitWS\async_and_thread_test\venv2\lib\site-packages\trio\_core\__init__.py", line 27, in <module>
    from ._run import (
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\chrisb\GitWS\async_and_thread_test\venv2\lib\site-packages\trio\_core\_run.py", line 34, in <module>
    from ._thread_cache import start_thread_soon
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\chrisb\GitWS\async_and_thread_test\venv2\lib\site-packages\trio\_core\_thread_cache.py", line 66, in <module>
    set_os_thread_name = get_os_thread_name_func()
  File "C:\Users\chrisb\GitWS\async_and_thread_test\venv2\lib\site-packages\trio\_core\_thread_cache.py", line 42, in get_os_thread_name_func
    libpthread = ctypes.CDLL(libpthread_path)
  File "C:\Users\chrisb\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
PermissionError: [WinError 5] Access is denied
```

**Comment by jakkdl** [comment] 2023-07-06 11:30
This is almost surely caused by #2470, and the particular lines in question are


https://github.com/python-trio/trio/blob/4816f0e47a17b996ca3d44319b593fa35320e55f/trio/_core/_thread_cache.py#L37-L42 
The function "should" give up after not finding the `pthread` library - or at least that's what happens on the test machines. But apparently your system *has* the `pthread` library, *but* you need elevated permission to access it? All the information I found at the time indicated that `pthread` would never be available on windows, and therefore the feature of renaming threads would not be possible (at least in this way) on windows.

It would be simple to just bail out with a `if sys.platform == "win32"; return` - but this does make me a bit curious if it's possible to get thread renaming possible, at least on systems like yours, given the correct permissions. I certainly don't have access to such a system though, unless one can modify the CI machines to have it, so I can just push a small PR that bails on any windows system and we can do a quick bugfix release.

**Comment by chrisbeardy** [comment] 2023-07-06 12:16
I wonder if its related to the fact i have WSL installed? If itts nott meant to work on windows anyway then I guess just bailing out is no harm

**Comment by jakkdl** [comment] 2023-07-06 12:56
Looking at it a bit more, it looks like you can get pthreads to run on windows:
https://stackoverflow.com/questions/7542286/how-to-run-pthreads-on-windows
https://stackoverflow.com/questions/19467455/how-to-set-up-pthreads-on-windows

So should maybe just guard that line with a `try: / except Exception:`

**Comment by A5rocks** [comment] 2023-07-06 23:54
For what it's worth, this doesn't error on my (Windows 11) machine which has WSL2 installed (and I think I had WSL1 temporarily, if that matters). `ctypes.util.find_library("pthread")` returns `None` too, as it should. I think gating it behind a Windows check is a nice quick fix. Looking at [pthreads-win32](https://sourceware.org/pthreads-win32/manual/pthread_setname_np.html) which seems to be the normal thing to use on Windows, it looks like it matches what we do unless there's some fancy BSD compat things going on. This means just catching the PermissionError should work too.

(sidenote) I just found https://pypi.org/project/pupil-pthreads-win/ which is a pretty funny package, honestly.

**Comment by jakkdl** [comment] 2023-07-07 09:21
Oh, if that works we could include that as an optional dependency? Would be lovely if either of you tried it and see if the associated tests in `trio/_tests/test_threads.py` passes all the way.
But yeah, sounds like catching the perm error is the way to go, and could also catch other esoteric problems on other systems.

**Comment by A5rocks** [comment] 2023-07-11 22:34
Should be fixed by https://github.com/python-trio/trio/pull/2693.

Patch release is going to come out soon-ish!

**Closed by A5rocks** 2023-07-11 22:34 UTC

**Comment by A5rocks** [comment] 2023-07-12 23:11
Hi, this should be fixed in https://pypi.org/project/trio/0.22.2!
