### ISSUE TITLE
Trio and PyCharm fighting over sys.excepthook

### ISSUE THREAD

**Issue by ernestum** [python-trio/trio#1553] opened 2020-05-25 14:15 UTC
The [Apport](https://wiki.ubuntu.com/Apport) error reporting mechanism of Ubuntu as well as PyCharm register custom `sys.excepthook`s. This causes the warning:
```
trio/_core/_multierror.py:472: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
```
and prevents uncaught multierrors from being printed properly.

I can reproduce this problem by simply running the following `test.pyt`:
```python
import trio
```
from within PyCharm or on any Ubuntu/Mint machine that has the `python3-apport` packet installed.

A possible workaround is to run `sys.excepthook = sys.__excepthook__` before importing trio but then the functionality of Apport/PyCharm will probably break.

Unfortunately there is no way to register multiple excepthooks in Python. However we might be able to "wrap" existing excepthooks instead of giving up in desparation?

**Comment by tjstum** [comment] 2020-05-26 00:46
Hi!

Thanks for this detailed report. This was recently fixed (original issue #1065, fixed in #1528). This was included in the release 0.15.0 (and subsequent 0.15.1).
Are you still seeing this issue even on the latest release?

**Comment by tjstum** [comment] 2020-05-26 00:47
Oh, I guess you also described an issue with PyCharm's excepthook! Maybe we should leave this open but rename/change the summary to narrow the scope.

**Comment by njsmith** [comment] 2020-05-26 01:46
Yeah, can you give more details on the PyCharm issue?

In PyCharm, what do you get if you do:

```python
print(repr(sys.excepthook))
print(repr(sys.__excepthook__))
```

?

**Comment by mozesa** [comment] 2020-05-26 05:50
```
<built-in function excepthook>
<built-in function excepthook>

Process finished with exit code 0
```

I hope it helped.

**Comment by njsmith** [comment] 2020-05-26 07:11
Huh. And what do you get from 'print(sys.excepthook is sys.__excepthook__)'?

**Comment by mozesa** [comment] 2020-05-26 07:18
I made a big misstake :(

```python
import sys

import trio


print(repr(sys.excepthook))
print(repr(sys.__excepthook__))
```

```text
<function trio_excepthook at 0x0000026AC55BE5E0>
<built-in function excepthook>
```

**Comment by tjstum** [comment] 2020-05-27 17:42
I was able to reproduce this using PyCharm. You have to use PyCharm's "debug" feature, not the normal "run" command:
```
Connected to pydev debugger (build 201.7223.92)
/.../site-packages/trio/_core/_multierror.py:472: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
  category=RuntimeWarning
<function _fallback_excepthook at 0x7fa29db23840>
<built-in function excepthook>
```
I think [this](https://github.com/JetBrains/intellij-community/blob/master/python/helpers/pydev/_pydevd_bundle/pydevd_breakpoints.py#L168) is their excepthook.

**Comment by mozesa** [comment] 2020-05-27 18:21
Yes it is true, in debug, always there is the warning.

**Comment by njsmith** [comment] 2020-05-27 23:32
Well, adding special monkeypatches for each random library is obviously a terrible long-term approach. But in the short term, that looks like a pretty easy special monkeypatch to do. Something like: check for the PyCharm excepthook, and if it's found then monkeypatch the `default_excepthook` variable inside that module.

**Comment by dhirschfeld** [comment] 2020-05-28 01:41
I have also noticed this warning in PyCharm but have so far ignored it 😬

**Comment by honglei** [comment] 2022-07-09 14:53
same warning for WingPro8, just ignore it.
```
C:\Python310\lib\site-packages\trio\_core\_multierror.py:511: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
  warnings.warn(
<bound method CWhenPrintExceptionSupport.__ExceptHook of <debug.tserver.dbgutils.CWhenPrintExceptionSupport object at 0x000001D295CE65C0>>
<built-in function excepthook>
False
```

**Comment by Zac-HD** [comment] 2023-10-17 11:21
Closing this in favor of https://github.com/agronholm/exceptiongroup/issues/23.

**Closed by Zac-HD** 2023-10-17 11:21 UTC
Labels: exception handling
