### ISSUE TITLE
fail_after raises TooSlow when it's cancelled

### ISSUE THREAD

**Issue by smurfix** [python-trio/trio#1054] opened 2019-05-16 12:09 UTC
This should not raise `TooSlow`. It wasn't. (Too slow, that is.)

```
import trio

async def killed(task_status=trio.TASK_STATUS_IGNORED):
    with trio.fail_after(2) as s:
        task_status.started(s)
        await trio.sleep(3)

async def test():
    async with trio.open_nursery() as n:
        s = await n.start(killed)
        s.cancel()

trio.run(test)
```

**Comment by oremanj** [comment] 2019-05-16 17:19
Duplicate of #698; feel free to add to the discussion there if you feel it doesn't adequately capture the issue you're seeing.

**Closed by oremanj** 2019-05-16 17:19 UTC
